backend:
  name: git-gateway
  branch: master
  repo: jennie/pangaea-g
  site_domain: cms.netlify.com
  base_url: https://api.netlify.com
# publish_mode: editorial_workflow
media_folder: images/uploads
collections:
  - name: reports
    label: Reports
    folder: collections/reports
    # extension: md
    create: true
    fields:
      - {label: Layout, name: layout, widget: select, options: ['topics-and-trends', 'inside-trade']}
      - {label: Type, name: type, widget: select, options: ['Topics & Trends', 'Inside Trade']}
      - {label: Title, name: title, widget: string}
      - {label: Volume/Month, name: volume, widget: string}
      - {label: Author, name: author, widget: string, default: Marla Weingarten}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}
      - name: authors
        label: Authors
        widget: list
        fields:
          - {label: Name, name: name, widget: string}
  - name: authors
    label: Authors
    folder: "collections/authors"
    create: true
    fields:
      - {name: name, label: Name}
      - {name: twitterHandle, label: "Twitter Handle"}
      - {name: bio, label: Bio, widget: text}
  - name: articles
    label: Articles
    folder: "collections/articles"
    create: true
    fields:
      - {name: title, label: Title, widget: string}
      - {name: body, label: Body, widget: markdown}
      - name: author
        label: Author
        widget: relation
        collection: authors
        searchFields: [name, twitterHandle]
        valueField: name
  - name: pages
    label: Pages
    folder: "collections/pages"
    create: true
    fields:
      - {name: title, label: Title, widget: string}
      - {label: Intro, name: intro, widget: object, fields: [{ label: Heading, name: heading, widget: string}, { label: Description, name: description, widget: text } ]}
      - {name: body, label: Body, widget: markdown}
      - {name: image, label: Feature Image, widget: image, required: false}
  - name: quotes
    label: Quotes
    folder: "collections/quotes"
    create: true
    fields:
      - {name: title, label: Title, widget: string}
      - {name: text, label: Text, widget: markdown}
      - {name: attribution, label: Attribution, widget: string}
      - name: page
        label: Page
        widget: relation
        collection: pages
        searchFields: [title]
        valueField: title



